# Generated by Django 2.0.5 on 2019-02-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('esal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eaddr', models.CharField(max_length=100)),
            ],
        ),
    ]
